- name: Restart grafana-agent
  become: true
  ansible.builtin.service:
    name: grafana-agent
    state: restarted
    enabled: true

- name: Restart prometheus-node-exporter
  become: true
  ansible.builtin.service:
    name: grafana-agent
    state: restarted
    enabled: true
